apiVersion: v1
kind: Pod
metadata:
  name: crashloop-demo
  namespace: troubleshooting-demos
spec:
  containers:
    - name: app
      image: nginx:1.27
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "echo starting; exit 1"]
