apiVersion: v1
kind: Pod
metadata:
  name: demo-get
  namespace: troubleshooting-demos
  labels:
    app: demo-get
    team: devops
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
