apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
  labels:
    app: emptydir-demo
    topic: volumes
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      volumeMounts:
        - name: scratch
          mountPath: /data
  volumes:
    - name: scratch
      emptyDir: {}