apiVersion: v1
kind: Service
metadata:
  name: notes-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: notes
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
